### ISSUE TITLE
AttributeError involving pandas reference

### ISSUE THREAD

**Issue by hamcruise** [opalytics/opalytics-ticdat#213]
Thanks for this great posting! 
I carefully followed the instruction. However, I got an AttribureError when I executed the py code. Can you please let me know how to fix this problem?

C:\Users\mham\Desktop\py_opl>python oil_blend.py -i oil_blend_sample_data.json -o oil-solution.xlsx
input file oil_blend_sample_data.json : output file oil-solution.xlsx
Traceback (most recent call last):
  File "oil_blend.py", line 88, in <module>
    standard_main(input_schema, solution_schema, solve)
  File "C:\Users\mham\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\utils.py", line 122, in standard_main
    return _standard_main_ticdat(input_schema, solution_schema, solve)
  File "C:\Users\mham\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\utils.py", line 216, in _standard_main_ticdat
    dat = input_schema.json.create_tic_dat(input_file)
  File "C:\Users\mham\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\jsontd.py", line 80, in create_tic_dat
    rtn = self.tic_dat_factory.TicDat(**tic_dat_dict)
  File "C:\Users\mham\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\ticdatfactory.py", line 614, in __init__
    if not (goodticdattable(v, t, lambda x : badticdattable.append(x))) :
  File "C:\Users\mham\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\ticdatfactory.py", line 771, in _good_tic_dat_table_for_init
    and not (pd.Series and isinstance(data_table, pd.Series)):
AttributeError: 'NoneType' object has no attribute 'Series'

**Comment by pjcpjc** [comment]
I just checked in something that hopefully fixes it. 

You have a couple of choices.

1. Install off the develop branch. I've never done this but I think [this](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch) is the right idea.
1. Install the `pandas` package. 

As far as I can tell, the error is occurring because you don't have `pandas` installed. A `pandas` installation isn't needed for general purpose use, and `ticdat` should give good error messages if you're trying to access functionality within `ticdat` that does require a `pandas` install.

I'm going to assume that one of these two workarounds fixes it for you, and thus my check in is correct. Feel free to ping me here and reopen if I'm wrong.

**Comment by hamcruise** [comment]
Thanks for the help. I have installed pandas and I have different errors. A further help will be appreciated.

C:\Users\AppData\Local\Programs\Python\Python37>cd C:\Users\Desktop\Py-OPL

C:\Users\Desktop\Py-OPL>python oil_blend.py -i oil_blend_sample_data.json -o oil-solution.xlsx
input file oil_blend_sample_data.json : output file oil-solution.xlsx
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\jsontd.py", line 105, in _create_jdict
    jdict = json.load(fp)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "oil_blend.py", line 88, in <module>
    standard_main(input_schema, solution_schema, solve)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\utils.py", line 122, in standard_main
    return _standard_main_ticdat(input_schema, solution_schema, solve)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\utils.py", line 215, in _standard_main_ticdat
    assert not input_schema.json.find_duplicates(input_file), "duplicate rows found"
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\jsontd.py", line 98, in find_duplicates
    jdict = self._create_jdict(json_file_path)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\jsontd.py", line 108, in _create_jdict
    (json_file_path, e.message))
AttributeError: 'JSONDecodeError' object has no attribute 'message'

**Comment by pjcpjc** [comment]
I can work on this at some point but it's probably not going to happen soon.

The AMPL functionality is much more important to me. OPL makes everything hard by refusing to create something equivalent to the `amplpy` package. 

Perhaps you can switch over to AMPL? As I say, they are actively working with me on `ticdat`. OPL's contribution has been to wish me luck, so they make it very hard for me to maintain this package for them.
